# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
sudo: required
cache: packages

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -q -y conda

script:
  - R CMD build .
  - R CMD install .
  - R -e 'reticulate::use_condaenv("r-reticulate")'
  - R -e 'altair::install_altair()'
  - R -e 'reticulate::py_config()'
  - R -e 'altair::check_altair()'
  - R CMD check *tar.gz

